### ISSUE TITLE
noetic rosinstall error with teleop_tools

### ISSUE THREAD

**Issue by gerardcanal** [pal-robotics/tiago_tutorials#40] opened 2023-02-14 20:58 UTC
Hi there,
Just realised the opensource simulations for tiago were released for noetic and gave it a go. I found that teleop_tools is set to get the noetic-devel branch in https://github.com/pal-robotics/tiago_tutorials/blob/18bbae1f29eee2ebe81c12e8449f602a1632ef75/tiago_public-noetic.rosinstall#L39 but the teleop_tools github doesn't seem to have the noetic_devel branch (or it has not yet been pushed).

It doesn't seem to be a big issue as it defaults to the default branch (and at least key_teleop seems to work).

**Comment by saikishor** [comment] 2023-02-15 09:15
Hello @gerardcanal,

Thank you for pointing it out. We are already working on the possible fixes and update to our .rosinstall. You can expect an update in the upcoming days.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by saikishor** [comment] 2023-02-16 08:18
Hello @gerardcanal,

The issue is currently resolved with the new changes. Thank you for your patience. 

Best Regards,
PAL Robotics Team.

**Closed as completed by saikishor** 2023-02-16 08:18 UTC
